
package bookIsbnVerify;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IsbnVerifyService", targetNamespace = "http://book/", wsdlLocation = "http://localhost:8444/IsbnVerify?wsdl")
public class IsbnVerifyService
    extends Service
{

    private final static URL ISBNVERIFYSERVICE_WSDL_LOCATION;
    private final static WebServiceException ISBNVERIFYSERVICE_EXCEPTION;
    private final static QName ISBNVERIFYSERVICE_QNAME = new QName("http://book/", "IsbnVerifyService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8444/IsbnVerify?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ISBNVERIFYSERVICE_WSDL_LOCATION = url;
        ISBNVERIFYSERVICE_EXCEPTION = e;
    }

    public IsbnVerifyService() {
        super(__getWsdlLocation(), ISBNVERIFYSERVICE_QNAME);
    }

    public IsbnVerifyService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ISBNVERIFYSERVICE_QNAME, features);
    }

    public IsbnVerifyService(URL wsdlLocation) {
        super(wsdlLocation, ISBNVERIFYSERVICE_QNAME);
    }

    public IsbnVerifyService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ISBNVERIFYSERVICE_QNAME, features);
    }

    public IsbnVerifyService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IsbnVerifyService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IsbnVerify
     */
    @WebEndpoint(name = "IsbnVerifyPort")
    public IsbnVerify getIsbnVerifyPort() {
        return super.getPort(new QName("http://book/", "IsbnVerifyPort"), IsbnVerify.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IsbnVerify
     */
    @WebEndpoint(name = "IsbnVerifyPort")
    public IsbnVerify getIsbnVerifyPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://book/", "IsbnVerifyPort"), IsbnVerify.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ISBNVERIFYSERVICE_EXCEPTION!= null) {
            throw ISBNVERIFYSERVICE_EXCEPTION;
        }
        return ISBNVERIFYSERVICE_WSDL_LOCATION;
    }

}
