
package bookIsbnVerify;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IsbnVerify", targetNamespace = "http://book/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IsbnVerify {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isbnVerify", targetNamespace = "http://book/", className = "bookIsbnVerify.IsbnVerify_Type")
    @ResponseWrapper(localName = "isbnVerifyResponse", targetNamespace = "http://book/", className = "bookIsbnVerify.IsbnVerifyResponse")
    @Action(input = "http://book/IsbnVerify/isbnVerifyRequest", output = "http://book/IsbnVerify/isbnVerifyResponse")
    public String isbnVerify(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

}
